### ISSUE TITLE
Crash on Android 6.0/5.1

### ISSUE THREAD

**Issue by dschuermann** [opentelecoms-org/lumicall#36]
Lumicall crashes on 2 test devices with Android 6.0 and Android 5.1. In both cases with ``DeadObjectException``.

```
07-07 11:16:26.844   194      194                   DEBUG  F  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-07 11:16:26.844   194      194                   DEBUG  F  Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MOB30H/2751534:user/release-keys'
07-07 11:16:26.845   194      194                   DEBUG  F  Revision: '11'
07-07 11:16:26.845   194      194                   DEBUG  F  ABI: 'arm'
07-07 11:16:26.845   194      194                   DEBUG  F  pid: 7423, tid: 8793, name: Thread-587  >>> org.lumicall.android <<<
07-07 11:16:26.845   194      194                   DEBUG  F  signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-07 11:16:26.893   194      194                   DEBUG  F  Abort message: 'art/runtime/thread.cc:1336] No pending exception expected: java.lang.NoSuchMethodError: no non-static method "Ljava/net/InetAddress;.<init>()V"'
07-07 11:16:26.893   194      194                   DEBUG  F  r0 00000000  r1 00002259  r2 00000006  r3 a02d6978
07-07 11:16:26.894   194      194                   DEBUG  F  r4 a02d6980  r5 a02d6930  r6 00000001  r7 0000010c
07-07 11:16:26.894   194      194                   DEBUG  F  r8 b4c7f800  r9 b4c7de44  sl a0dcf15b  fp b4c63450
07-07 11:16:26.894   194      194                   DEBUG  F  ip 00000006  sp a02d56c8  lr b6cc5b61  pc b6cc7f50  cpsr 40070010
07-07 11:16:26.925   194      194                   DEBUG  F  backtrace:
07-07 11:16:26.925   194      194                   DEBUG  F  #00 pc 00041f50  /system/lib/libc.so (tgkill+12)
07-07 11:16:26.926   194      194                   DEBUG  F  #01 pc 0003fb5d  /system/lib/libc.so (pthread_kill+32)
07-07 11:16:26.926   194      194                   DEBUG  F  #02 pc 0001c30f  /system/lib/libc.so (raise+10)
07-07 11:16:26.926   194      194                   DEBUG  F  #03 pc 000194c1  /system/lib/libc.so (__libc_android_abort+34)
07-07 11:16:26.926   194      194                   DEBUG  F  #04 pc 000174ac  /system/lib/libc.so (abort+4)
07-07 11:16:26.926   194      194                   DEBUG  F  #05 pc 00333971  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+228)
07-07 11:16:26.926   194      194                   DEBUG  F  #06 pc 000f45fb  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
07-07 11:16:26.926   194      194                   DEBUG  F  #07 pc 000f08d1  /system/lib/libart.so (_ZN3art7BarrierD2Ev+216)
07-07 11:16:26.927   194      194                   DEBUG  F  #08 pc 0035b473  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+162)
07-07 11:16:26.927   194      194                   DEBUG  F  #09 pc 00333a35  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+424)
07-07 11:16:26.927   194      194                   DEBUG  F  #10 pc 000f45fb  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
07-07 11:16:26.927   194      194                   DEBUG  F  #11 pc 0034f0b3  /system/lib/libart.so (_ZNK3art6Thread24AssertNoPendingExceptionEv.part.170+378)
07-07 11:16:26.927   194      194                   DEBUG  F  #12 pc 00136aab  /system/lib/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mirror11ClassLoaderEEE+34)
07-07 11:16:26.928   194      194                   DEBUG  F  #13 pc 0029d4c1  /system/lib/libart.so (_ZN3art3JNI9FindClassEP7_JNIEnvPKc+812)
07-07 11:16:26.928   194      194                   DEBUG  F  #14 pc 00002b53  /data/app/org.lumicall.android-1/lib/arm/libOSNetworkSystem.so (_Z17jniThrowExceptionP7_JNIEnvPKcS2_+10)
07-07 11:16:26.928   194      194                   DEBUG  F  #15 pc 00b2970b  /data/app/org.lumicall.android-1/oat/arm/base.odex (offset 0x98a000)
07-07 11:16:27.330   194      194                   DEBUG  F  Tombstone written to: /data/tombstones/tombstone_02
07-07 11:16:27.330   194      194                   DEBUG  E  AM write failed: Broken pipe
07-07 11:16:27.330   777      794            BootReceiver  I  Copying /data/tombstones/tombstone_02 to DropBox (SYSTEM_TOMBSTONE)
07-07 11:16:27.338   777      8798        ActivityManager  W  Force finishing activity org.lumicall.android/org.sipdroid.sipua.ui.InCallScreen
07-07 11:16:27.352   777      788             WindowState  I  WIN DEATH: Window{96640ce u0 org.lumicall.android/org.sipdroid.sipua.ui.Sipdroid}
07-07 11:16:27.358   777      1330            WindowState  I  WIN DEATH: Window{9774972 u0 org.lumicall.android/org.sipdroid.sipua.ui.InCallScreen}
07-07 11:16:27.358   777      8798        ActivityManager  W  Exception thrown during pause
07-07 11:16:27.358   777      8798        ActivityManager  W  android.os.DeadObjectException
07-07 11:16:27.358   777      8798        ActivityManager  W  at android.os.BinderProxy.transactNative(Native Method)
07-07 11:16:27.358   777      8798        ActivityManager  W  at android.os.BinderProxy.transact(Binder.java:503)
07-07 11:16:27.358   777      8798        ActivityManager  W  at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
07-07 11:16:27.358   777      8798        ActivityManager  W  at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
07-07 11:16:27.358   777      8798        ActivityManager  W  at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
07-07 11:16:27.358   777      8798        ActivityManager  W  at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
07-07 11:16:27.358   777      8798        ActivityManager  W  at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
07-07 11:16:27.358   777      8798        ActivityManager  W  at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12037)
07-07 11:16:27.358   777      8798        ActivityManager  W  at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11933)
07-07 11:16:27.358   777      8798        ActivityManager  W  at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12622)
07-07 11:16:27.358   777      8798        ActivityManager  W  at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12129)
07-07 11:16:27.358   777      8798        ActivityManager  W  at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
07-07 11:16:27.359   777      889             WifiService  D  Client connection lost with reason: 4
07-07 11:16:27.361   777      8798        ActivityManager  I  Restarting because process died: ActivityRecord{f5b8275 u0 org.lumicall.android/org.sipdroid.sipua.ui.Sipdroid t736}
07-07 11:16:27.363   777      8798        ActivityManager  W  Exception when starting activity org.lumicall.android/org.sipdroid.sipua.ui.Sipdroid
07-07 11:16:27.363   777      8798        ActivityManager  W  android.os.DeadObjectException
07-07 11:16:27.363   777      8798        ActivityManager  W  at android.os.BinderProxy.transactNative(Native Method)
07-07 11:16:27.363   777      8798        ActivityManager  W  at android.os.BinderProxy.transact(Binder.java:503)
07-07 11:16:27.363   777      8798        ActivityManager  W  at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:826)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1284)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityStackSupervisor.startSpecificActivityLocked(ActivityStackSupervisor.java:1384)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:1969)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:1554)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:1537)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:922)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12037)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11933)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12622)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12129)
07-07 11:16:27.363   777      8798        ActivityManager  W  at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
07-07 11:16:27.404   213      213                  Zygote  I  Process 7423 exited due to signal (6)
07-07 11:16:27.418   777      784    KeyguardDisableHan..  W  cleaning up leaked reference: Sipdroid
07-07 11:16:27.424   777      8798        ActivityManager  W  Scheduling restart of crashed service org.lumicall.android/.ganglia.GMonitorService in 1000ms
07-07 11:16:27.424   777      8798        ActivityManager  W  Scheduling restart of crashed service org.lumicall.android/org.sipdroid.sipua.ui.RegisterService in 11000ms
07-07 11:16:27.437   777      8798        ActivityManager  I  Start proc 8801:org.lumicall.android/u0a87 for activity org.lumicall.android/org.sipdroid.sipua.ui.Sipdroid
07-07 11:16:27.437   777      1572        ActivityManager  W  Spurious death for ProcessRecord{f5b6f04 8801:org.lumicall.android/u0a87}, curProc for 7423: null

```

**Comment by dschuermann** [comment]
Looks like this happens only with the Google Play release, not with the F-Droid release.
