### ISSUE TITLE
SQLiteConstraintException: ENUMSuffix.suffix may not be NULL (code 19)

### ISSUE THREAD

**Issue by eileenfan** [opentelecoms-org/lumicall#60]
//package name: org.lumicall.android
//version: 1.12.16
 android.database.sqlite.SQLiteConstraintException: ENUMSuffix.suffix may not be NULL (code 19)
 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
 	at org.lumicall.android.db.DBObject.commit(DBObject.java:33)
 	at org.lumicall.android.db.LumicallDataSource.persistENUMSuffix(LumicallDataSource.java:73)
 	at org.lumicall.android.preferences.ENUMSuffixSettings.persistObject(ENUMSuffixSettings.java:34)
 	at org.lumicall.android.preferences.ENUMSuffixSettings.persistObject(ENUMSuffixSettings.java:30)
 	at org.lumicall.android.preferences.DBObjectSettings.setBeanValue(DBObjectSettings.java:105)
 	at org.lumicall.android.preferences.DBObjectSettings$MyListener.onPreferenceChange(DBObjectSettings.java:132)
 	at android.preference.Preference.callChangeListener(Preference.java:895)
 	at android.preference.EditTextPreference.onDialogClosed(EditTextPreference.java:141)
 	at android.preference.DialogPreference.onDismiss(DialogPreference.java:383)
 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1232)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by pranavjain** [comment]
Hi @eileenfan ,
Could you please elaborate the issues you are facing? I tried going through the multiple issues you have created but couldn't understand.
